- name: Connect to win servers
  tasks:
    - name: Create User Koks
      microsoft.ad.user:
        name: '{{ lastname }} {{ firstname }}'
        firstname: '{{ firstname }}'
        lastname: '{{ lastname }}'
        display_name: '{{ lastname }} {{ firstname }}'
        password: password
        upn: '{{ lastname.lower() }}.{{ firstname[0].lower() }}@example.com'          # Generate UPN with variable and python
        sam_account_name: '{{ lastname.lower() }}.{{ firstname[0].lower() }}'
        email: '{{ lastname.lower() }}.{{ firstname[0].lower() }}@example.com'
        path: path
        state: present
      register: result

- name: Test
  tasks:
    - name: Return result
      ansible.builtin.debug:
        msg: '{{ result }}'
